### ISSUE TITLE
It should be noted in the docs that libcurl4-openssl-dev is required

### ISSUE THREAD

**Issue by deanhouseholder** [jliesch/ofxget#2]
When trying to run `make` it would continue to fail with

> ofxget.cc:8:10: fatal error: curl/curl.h: No such file or directory
> #include <curl/curl.h>
>          ^~~~~~~~~~~~~
> compilation terminated.
> Makefile:15: recipe for target 'ofxget.o' failed

I was able to fix it on Ubuntu by running:

`apt-get install libcurl4-openssl-dev`

It would be helpful to add this to the README.md

**Comment by jliesch** [comment]
Thanks for the suggestion. Done.
