### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ryantm** [jliesch/ofxget#5]
I was looking into packaging this for [nixpkgs](https://github.com/nixos/nixpkgs) and there doesn't appear to be a license. Could you add a license?

**Comment by jliesch** [comment]
Hello. I appreciate the interest. but you should probably read this post here: http://www.ofxhome.com/ofxforum//viewtopic.php?id=49843

tl;dr is that I am not actively maintaining this project and will eventually shut it down.
